name: Notify on Repository Update

on:
  push:
    branches:
      - main  # Monitor the main branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install sendmail
        run: sudo apt-get install -y sendmail

      # Step 3: Detect new files and send an email
      - name: Send email on new files
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: "rajugoddumuri@gmail.com"
        run: |
          echo "Checking for new files..."
          git diff --name-only HEAD^ HEAD | grep '^' || echo "No new files."
          if git diff --name-only HEAD^ HEAD | grep -E '.+'; then
            echo "New files detected. Sending email..."
            echo -e "Subject: New Files Added\n\nThe following files were added:\n$(git diff --name-only HEAD^ HEAD)" | \
            sendmail -v -f "$EMAIL_SENDER" -au"$EMAIL_SENDER" -ap"$EMAIL_PASSWORD" "$EMAIL_RECEIVER"
          else
            echo "No new files detected."
