name: Notify on Repository Update

on:
  push:
    branches:
      - main  # Replace with the branch you want to monitor

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run a custom script to detect changes and send email
      - name: Notify on new files
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: "rajugoddumuri@gmail.com"  # Replace with your recipient email
        run: |
          echo "Checking for new files..."
          git diff --name-only HEAD^ HEAD | grep '^' || echo "No new files."
          if git diff --name-only HEAD^ HEAD | grep -E '.+'; then
            echo "New files detected. Sending email..."
            echo -e "Subject: New Files Added\n\nThe following files were added:\n$(git diff --name-only HEAD^ HEAD)" | \
            sendmail -v -f "$EMAIL_SENDER" -au"$EMAIL_SENDER" -ap"$EMAIL_PASSWORD" "$EMAIL_RECEIVER"
          else
            echo "No new files added."
          fi
